development:
  username: root
  adapter: mysql
  database: spots_development
  host: localhost
  password: ''
test:
  username: root
  adapter: mysql
  database: spots_test
  host: localhost
  password: ''
production: 
  username: root
  adapter: mysql
  database: spots_production
  host: localhost
  password: ''

